rotating cube done
popov-p/computer-graphics pull request #3
Opened 2024-04-05 17:30 UTC by popov-p

2024-04-08 07:49 UTC, Sairsey requested changes

2024-04-08 07:49 UTC, Sairsey commented on Window/Input.h
> +#include <dinput.h>
Добрый день. У вас при сборке проекта появляются Warning-и. Исправьте пожалуйста

2024-04-08 07:49 UTC, Sairsey commented on Window/Window.cpp
> +	pRenderer->ReleasePointers();
Давайте лучше просто добавим деструктор этому классу. И добавьте проверку на "не отпущенные" Live Objects

2024-04-10 07:33 UTC, popov-p commented on Window/Input.h
> +#include <dinput.h>
В настройках проекта я поставил warning-level 4. Warning-и, которые выдаёт вижуалка в Error List, отсутствуют. Если речь идёт о предупреждениях при сборке проекта (предупреждения связаны с версией dinput), то их я пофиксил.

2024-04-10 07:33 UTC, popov-p commented on Window/Window.cpp
> +	pRenderer->ReleasePointers();
Исправил.

2024-04-11 08:45 UTC, Sairsey requested changes

2024-04-11 08:45 UTC, Sairsey commented on Window/Renderer.cpp
> +	if (flags & D3D11_CREATE_DEVICE_DEBUG) {
Cуть этой проверки в том, чтобы проверить что ты не забыли освободить ресурсы, которые создали в рамках работы приложения. Не очень много смысла имеет проверять "удалены ли ресурсы" **ДО** их удаления. Давайте передвинем после ваших SAFE_RELEASE. Помимо этого, данная проверка должна работать только в DEBUG конфигурации

2024-04-11 08:48 UTC, Sairsey commented on Window/Renderer.cpp
> +	if (flags & D3D11_CREATE_DEVICE_DEBUG) {
Ваши не удаленные ресурсы будут отображаться  в окошке Output в VS примерно так
```
D3D11 WARNING: Live ID3D11Device at 0x0000022CFDCAE700, Refcount: 14 [ STATE_CREATION WARNING #441: LIVE_DEVICE]
D3D11 WARNING: 	Live ID3D11Context at 0x0000022CFDCB2B50, Refcount: 1, IntRef: 1 [ STATE_CREATION WARNING #2097226: LIVE_CONTEXT]
D3D11 WARNING: 	Live ID3DDeviceContextState at 0x0000022CFDE63E40, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #3145742: LIVE_DEVICECONTEXTSTATE]
D3D11 WARNING: 	Live ID3D11BlendState at 0x0000022CFDE6F1A0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #435: LIVE_BLENDSTATE]
D3D11 WARNING: 	Live ID3D11DepthStencilState at 0x0000022CFDE6F6F0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #436: LIVE_DEPTHSTENCILSTATE]
D3D11 WARNING: 	Live ID3D11RasterizerState at 0x0000022CFDE6F8E0, Refcount: 1, IntRef: 1 [ STATE_CREATION WARNING #437: LIVE_RASTERIZERSTATE]
D3D11 WARNING: 	Live ID3D11Sampler at 0x0000022CFDE6FAE0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #434: LIVE_SAMPLER]
D3D11 WARNING: 	Live ID3D11Query at 0x0000022CFDE6FCD0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #438: LIVE_QUERY]
D3D11 WARNING: 	Live IDXGISwapChain at 0x0000022CFDE6FED0, Refcount: 1 [ STATE_CREATION WARNING #442: LIVE_SWAPCHAIN]
D3D11 WARNING: 	Live ID3D11Texture2D at 0x0000022CFDE744A0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #425: LIVE_TEXTURE2D]
D3D11 WARNING: 	Live ID3D11Texture2D at 0x0000022CFDE75040, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #425: LIVE_TEXTURE2D]
D3D11 WARNING: 	Live ID3D11Fence at 0x0000022CFDE75BE0, Refcount: 0, IntRef: 1 [ STATE_CREATION WARNING #3146250: LIVE_FENCE]
D3D11 WARNING: 	Live ID3D11RenderTargetView at 0x0000022CFDE7C1C0, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #428: LIVE_RENDERTARGETVIEW]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000022CFDE7E410, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000022CFDE85B30, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11VertexShader at 0x0000022CFDE888A0, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #430: LIVE_VERTEXSHADER]
D3D11 WARNING: 	Live ID3D11PixelShader at 0x0000022CFDE89900, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #432: LIVE_PIXELSHADER]
D3D11 WARNING: 	Live ID3D11InputLayout at 0x0000022CFDE8D990, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #433: LIVE_INPUTLAYOUT]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000022CFDE8DC00, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
D3D11 WARNING: 	Live ID3D11Buffer at 0x0000022CFDE8DFE0, Refcount: 1, IntRef: 0 [ STATE_CREATION WARNING #423: LIVE_BUFFER]
```
Как вы догадываетесь, их быть не должно :)

2024-04-11 16:20 UTC, popov-p commented on Window/Renderer.cpp
> +	if (flags & D3D11_CREATE_DEVICE_DEBUG) {
Исправил.

2024-04-12 14:46 UTC, Sairsey commented
Лабораторная зачтена

2024-04-12 14:46 UTC, Sairsey approved these changes
.

2024-04-12 14:47 UTC, merged